version: 2
jobs:
  build:
    docker:
      - image: markhibberd/haskell-circleci:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - restore_cache:
          keys:
            - 'mafia-oauth2-jwt-bearer-'
      - run:
          name: 'build'
          command: 'cabal update && ./mafia build'
      - save_cache:
          key: 'mafia-oauth2-jwt-bearer-{{ epoch }}'
          paths:
            - '/root/.mafia'
      - run:
          name: 'test'
          command: 'mafia test'
